ci:
  collect:
    staticDistDir: './dist/apps/bluetouch-web'
  assert:
    preset: lighthouse:no-pwa
  upload:
    # upload options here
  server:
    # server options here
  wizard:
    # wizard options here
