ci:
  collect:
    settings:
      onlyCategories: ["performance"]
      throttlingMethod: ["devtools"]
    numberOfRuns: 1
    staticDistDir: "./dist/apps/bluetouch-web"

  budgets:
    - path: "categories.performance"
  assert:
    preset: "lighthouse:recommended"
    audits:
      metrics: "off"
    assertions:
      categories.pwa: "off"
      bypass: ["warn", { "minScore": 0 }]
      is-on-https: ["warn", { "minScore": 0 }]
      accessibility: ["warn", { "minScore": 0 }]
      best-practices: ["warn", { "minScore": 0 }]
      seo: ["warn", { "minScore": 0 }]
