ci:
  collect:
    settings:
      onlyCategories: [ "performance" ]
      throttlingMethod: ["devtools"]
    numberOfRuns: 1
    staticDistDir: ./dist/apps/bluetouch-web
  assert:
    preset: lighthouse:no-pwa
    assertions:
      categories:performance: ["warn", { "minScore": 0.1 }]
  upload:
    # upload options here
  server:
    # server options here
  wizard:
    # wizard options here
