ci:
  collect:
    settings:
      onlyCategories: ["performance"]
      throttlingMethod: ["devtools"]
    numberOfRuns: 1
    staticDistDir: "./dist/apps/bluetouch-web"

  budgets:
    - path: "categories.performance"
      metrics:
        first-contentful-paint: 0
        largest-contentful-paint: 0
        first-meaningful-paint: 0
        speed-index: 0
        interactive: 0
        total-blocking-time: 0
        cumulative-layout-shift: 0

  assert:
    preset: "lighthouse:recommended"
    audits:
      metrics: "off"
    assertions:
      categories.pwa: "off"
      bypass: ["warn", { "minScore": 0 }]
      is-on-https: ["warn", { "minScore": 0 }]
      accessibility: ["warn", { "minScore": 0 }]
      best-practices: ["warn", { "minScore": 0 }]
      seo: ["warn", { "minScore": 0 }]
