name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install Nx CLI
        run: npm install -g nx

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: nx run bluetouch-web:build:production --buildOptimizer=true --namedChunks=true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/bluetouch-web # Replace "bluetouch-web" with the name of your Angular project

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
