name: lhci
on: [push]

jobs:
  lighthouseci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set GitHub token
        uses: actions/setup-secrets@v1
        with:
          secrets:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install -g nx && npm install && npm install -g @lhci/cli@0.12.0

      - run: nx run bluetouch-web:build:production --buildOptimizer=true --namedChunks=true

      - run: lhci autorun --upload.target=temporary-public-storage --token "${{ secrets.GITHUB_TOKEN }}"
